# Generated by Django 3.2.6 on 2021-09-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210923_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='why', unique=True),
            preserve_default=False,
        ),
    ]
