# Generated by Django 3.2.6 on 2021-09-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='k', max_length=300),
            preserve_default=False,
        ),
    ]
