# Generated by Django 3.2.9 on 2021-12-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211222_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='master_user_id',
            new_name='master_user',
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('master_user', 'following_user')},
        ),
    ]
