# Generated by Django 3.2.6 on 2021-09-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='k', unique=True),
            preserve_default=False,
        ),
    ]
