# Generated by Django 3.2.6 on 2021-10-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='1', max_length=254),
            preserve_default=False,
        ),
    ]
